databases:
  - name: matchmaking-db
    databaseName: matchmaking
    plan: free

services:
  - type: web
    name: matchmaking-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: matchmaking-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false

